---
- name: Create user
  hosts: "{{ mysql_host }}"
  mysql_user: 
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_privileges }}"
    host: "{{ mysql_host_access }}"
    state: "{{ state }}"
    login_user: 'root'
    login_password: "{{ mysql_root_password | default(omit) }}"

- name: "Update last operation"
  asb_last_operation:
    description: "30%: Done"

- name: Create database
  hosts: "{{ mysql_host }}"
  mysql_db:
    name: "{{ mysql_db }}" 
    state: "{{ state }}"
    collation: 'utf8_general_ci'
    encoding: 'utf8'
    login_user: 'root'
    login_password: "{{ mysql_root_password | default(omit) }}"

- name: "Update last operation"
  asb_last_operation:
    description: "60%: Done"

- name: encode bind credentials
  asb_encode_binding:
      fields:
        DB_USER: "{{ mysql_user }}"
        DB_PASSWORD: "{{ mysql_password }}"
        DB_NAME: "{{ mysql_database }}"
  when: state == "present"

- name: "Update last operation"
  asb_last_operation:
    description: "100%: Done"
