---

- name: Install MySQL
  yum: name={{ item }} state=present
  with_items:
    - mysql55-mysql
    - mysql55-mysql-server
    - MySQL-python

- name: Start MySQL
  service: name=mysqld state=started enabled=yes
