apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    # minishift
    app: openshift-automation-service-broker
    # ocp 3.10
    # app: openshift-ansible-service-broker
  name: broker-config
  # minishift
  namespace: openshift-automation-service-broker
  # ocp 3.10
  # namespace: openshift-ansible-service-broker
data:
  broker-config: |
    registry:
      - type: local_openshift
        name: localregistry
        namespaces: ['openshift']
        white_list: [.*-apb]

    dao:
      type: crd
    log:
      stdout: true
      level: info
      color: true
    openshift:
      host: ""
      ca_file: ""
      bearer_token_file: ""
      # minishift
      namespace: openshift-automation-service-broker
      # ocp 3.10
      # namespace: openshift-ansible-service-broker
      sandbox_role: edit
      image_pull_policy: Always
      keep_namespace: false
      keep_namespace_on_error: false
    broker:
      dev_broker: false
      bootstrap_on_startup: true
      refresh_interval: 60s
      launch_apb_on_bind: false
      output_request: false
      recovery: false
      ssl_cert_key: /etc/tls/private/tls.key
      ssl_cert: /etc/tls/private/tls.crt
      auto_escalate: False
      auth:
        - type: basic
          enabled: false