# Discovered from CustomResource metadata
name: "{{ meta.name }}"
namespace: "{{ meta.namespace }}"

# Mysql image vars
image: docker-registry.default.svc:5000/openshift/mysql
mysql_version: latest

# Openshift service of the mysql deployment
mysql_service: mysql

# Backup capacity
volume_capacity: 1Gi

# Take backup every {{ intervalMinutes }} minutes.
# A value of 0 means only take one backup
interval_minutes: 0
