---
kind: Template
apiVersion: v1
metadata:
  name: "${APPLICATION_NAME}"
  annotations:
    openshift.io/display-name: Ansible Jenkins Agent
    description: "${APPLICATION_NAME} build pod template pre-configured to use a jenkins slave in the
      same project/namespace"
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      application: "${APPLICATION_NAME}"
      group: "${APPLICATION_GROUP}"
      build: "${APPLICATION_NAME}"
      type: image
    name: "${APPLICATION_NAME}"
    namespace: "${APPLICATION_NAMESPACE}"
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: "${APPLICATION_NAME}:latest"
        namespace: openshift
    runPolicy: Serial
    source:
      contextDir: "${SOURCE_CONTEXT_DIR}"
      git:
        ref: "${SOURCE_REPOSITORY_REF}"
        uri: "${SOURCE_REPOSITORY_URL}"
      type: Git
    strategy:
      dockerStrategy:
        noCache: true
        forcePull: true
        dockerfilePath: "${DOCKERFILE_PATH}"
        from:
          kind: DockerImage
          name: "${BUILDER_IMAGE_NAME}:latest"
      type: Docker
    failedBuildsHistoryLimit: 5
    successfulBuildsHistoryLimit: 5
    triggers: {}
parameters:
- name: APPLICATION_NAME
  value: database-provision-apb
- name: APPLICATION_GROUP
  value: widget-factory
- name: APPLICATION_NAMESPACE
  value: widget-factory
- name: SOURCE_REPOSITORY_URL
  value: https://github.com/srang/rh-openshift-ansible-broker-lab
- name: SOURCE_REPOSITORY_REF
  value: master
- name: SOURCE_CONTEXT_DIR
  value: database-provision-apb
- name: BUILDER_IMAGE_NAME
  value: registry.access.redhat.com/openshift3/apb-base
- name: DOCKERFILE_PATH
  value: Dockerfile

