apiVersion: v1
kind: Template
labels:
  template: widget-jenkins-agent-pipeline
metadata:
  name: widget-jenkins-agent-pipeline
objects:
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    labels:
      application: "${BUILDER_NAME}-pipeline"
      group: "${APPLICATION_NAME}"
    name: "${BUILDER_NAME}-pipeline"
    namespace: "${APPLICATION_NAMESPACE}"
  spec:
    source:
      type: Git
      git:
        uri: ${APPLICATION_SOURCE_REPOSITORY_URL}
        ref: ${APPLICATION_SOURCE_REPOSITORY_REF}
      contextDir: ${BUILDER_CONTEXT_DIR}
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
        jenkinsfilePath: ${PIPELINE_SCRIPT}
        env:
        - name: "APPLICATION_SOURCE_REPOSITORY_URL"
          value: "${APPLICATION_SOURCE_REPOSITORY_URL}"
        - name: "BUILDER_CONTEXT_DIR"
          value: "${BUILDER_CONTEXT_DIR}"
parameters:
- name: APPLICATION_NAME
  value: widget-factory
- name: BUILDER_NAME
  value: widget-jenkins-agent
- name: APPLICATION_NAMESPACE
  value: widget-factory
- name: APPLICATION_SOURCE_REPOSITORY_URL
  value: https://github.com/srang/rh-openshift-ansible-broker-lab.git
- name: APPLICATION_SOURCE_REPOSITORY_REF
  required: true
- name: BUILDER_CONTEXT_DIR
  value: widget-jenkins-agent
- name: PIPELINE_SCRIPT
  value: Jenkinsfile
