---
- name: install mysql
  hosts: bastion-server
  tasks:
  - name: install mysql-server
    become: yes
    become_method: sudo
    yum:
      name:
      - mariadb
      - mariadb-server
      - MySQL-python
      state: present
    notify: restart mysql

  - name: ensure mysqld running
    service:
      name: mariadb
      state: started
      sleep: 5
    become: yes
    become_method: sudo

  - name: widget database
    mysql_db:
      name: 'widget'
      state: 'present'
      collation: 'utf8_general_ci'
      encoding: 'utf8'
      login_user: 'root'

  - name: widget user
    mysql_user:
      name: 'widget'
      host: '*'
      password: 'widget01'
      priv: '*.widget:ALL,GRANT'
      state: present
      login_user: 'root'

  - name: remove test database
    mysql_db:
      name: 'test'
      state: 'absent'


  handlers:
  - name: restart mysql
    service:
      name: mariadb
      state: restarted
      enabled: yes
      sleep: 5
    become: yes
    become_method: sudo
