---

- name: Converge
  hosts: localhost
  connection: local
  vars:
    deploy_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"
    mysql_custom_resource: "{{ lookup('file', '/'.join([deploy_dir, 'crds/mysql/mysql_cr.yaml'])) | from_yaml }}"
  tasks:
  - name: Create the Mysql resource
    k8s:
      namespace: '{{ namespace }}'
      definition: "{{ lookup('file', '/'.join([deploy_dir, 'crds/mysql/mysql_cr.yaml'])) }}"

  - name: Give the Mysql deployment a chance to become ready
    pause:
      seconds: 120

- import_playbook: "{{ playbook_dir }}/../default/asserts.yml"
