# Discovered from CustomResource metadata
name: "{{ meta.name | default('mysqlbackup') }}"
namespace: "{{ meta.namespace | default('mysql') }}"

# Mysql image vars
image: docker-registry.default.svc:5000/openshift/mysql
mysql_version: latest

# Openshift service of the mysql deployment
mysql_deployment: mysql

# PVC containing the backup contents
mysql_backup_pvc: mysqlbackup