apiVersion: v1
kind: Service
metadata:
  name: data-service
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: data-service
    release: v1
  type: ClusterIP
