---
- name: Install Software
  hosts: all
  remote_user: ec2-user
  gather_facts: false
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  tasks:
    - name: Check for Python
      raw: test -e /usr/bin/python
      changed_when: false
      failed_when: false
      register: check_python

    - name: Install Python
      become: yes
      raw: yum -y install python3
      when: check_python.rc != 0

    - name: Install Ansible
      become: yes
      pip:
        name: ansible
        state: present

    - name: Install Docker
      become: yes
      dnf:
        name: docker
        state: present

    - name: Install git
      become: yes
      dnf:
        name: git
        state: present

    - name: Download operator-sdk
      become: yes
      get_url:
        url: "https://github.com/operator-framework/operator-sdk/releases/download/v0.5.0/operator-sdk-v0.5.0-x86_64-linux-gnu"
        dest: "/usr/local/bin/operator-sdk"
        mode: 0110
        owner: 1001
        group: users
 
    - name: Create users group
      become: yes
      group:
        name: users
        state: present

    - name: Add user to users group
      become: yes
      user:
        name: ec2-user
        append: yes
        groups: users
