---

- name: database-provision playbook to deprovision the application
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    apb_action: deprovision
    state: 'absent'
  roles:
  - role: database-provision
    