---

- name: database-provision playbook to provision the application
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    apb_action: provision
    state: 'present'
  roles:
  - role: ansibleplaybookbundle.asb-modules
  - role: database-provision-apb
    