# Discovered from CustomResource metadata
name: "{{ meta.name | default('mysql') }}"
namespace: "{{ meta.namespace | default('mysql') }}"

# present - install
# absent - uninstall
state: present

mysql_database: widgetfactory
mysql_password: admin123
mysql_user: admin

# Database capacity
volume_capacity: 1Gi

memory_limit: 512Mi

mysql_version: latest
image_namespace: openshift
