apiVersion: v1
kind: Template
labels:
  template: widget-factory-deploy-template
metadata:
  annotations:
    description: Template for deploying widget-factory
    tags: demo,java
  name: widget-factory-deploy-template
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      application: ${APPLICATION_NAME}-db
      group: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-db-svc
    namespace: ${APPLICATION_NAMESPACE}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      application: ${APPLICATION_NAME}
      group: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
    namespace: ${APPLICATION_NAMESPACE}
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      application: ${APPLICATION_NAME}
      group: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      application: ${APPLICATION_NAME}
    type: ClusterIP
parameters:
- name: APPLICATION_NAME
  value: widget-factory
- name: APPLICATION_RELEASE
  required: true
- name: APPLICATION_NAMESPACE
  value: widget-factory
